Back/src/app.module.ts
Back/src/auth/auth.repository.ts
Back/src/auth/auth.service.ts
Back/src/person/dtos/createPerson.dto.ts
Back/src/person/entities/person.entity.ts
Back/src/person/person.controller.ts
Back/src/person/person.module.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Back/src/role/dtos/role.dto.ts
Back/src/role/role.controller.ts
Back/src/role/role.module.ts

Some changes for SignUp and SignIn functions

FIX/ SignUp and SignIn

---

Back/src/app.module.ts
Back/src/system_configs/dto/update-system_config.dto.ts
Back/src/system_configs/entities/system_config.entity.ts
Back/src/system_configs/system_configs.controller.spec.ts
Back/src/system_configs/system_configs.controller.ts
Back/src/system_configs/system_configs.module.ts
Back/src/system_configs/system_configs.repository.ts
Back/src/system_configs/system_configs.service.spec.ts
Back/src/system_configs/system_configs.service.ts

added system config module in order to improve the management of specifics params in system

add system config module

---

Back/src/auth/auth.service.ts
Back/src/person/person.controller.ts
Back/src/person/person.service.ts

Some fixes for People and Auth

Some fixes for People and Auth

---

Back/src/main.ts

FIX/ remove auth0 importations

FIX/ remove auth0 importations

---

Back/src/appointments/appointments.controller.ts
Back/src/appointments/dto/create-appointment.dto.ts
Back/src/person/entities/patient.entity.ts

minimal fixes from Jorge branch

---

Back/src/auth/auth.controller.ts
Back/src/auth/interceptors/signUp.interceptor.ts
Back/src/person/dtos/createPerson.dto.ts

ADD/ SignUp interceptor

---

Back/src/app.module.ts
Back/src/config/typeorm.ts
Back/src/person/entities/patient.entity.ts

FIX/ patient

---

Back/src/auth/auth.controller.ts
Back/src/auth/auth.repository.ts
Back/src/auth/auth.service.ts
Back/src/auth/dtos/restoreAuth.dto.ts
Back/src/auth/dtos/updatePassword.dto.ts
Back/src/auth/entities/auth.entity.ts
Back/src/person/dtos/createDentist.dto.ts
Back/src/person/dtos/updatePerson.dto.ts
Back/src/person/entities/dentist.entity.ts
Back/src/person/person.controller.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Back/src/role/role.controller.ts
Back/src/role/role.repository.ts
Back/src/role/role.service.ts

Complete some CRUD

---

Back/src/auth/auth.controller.ts
Back/src/person/dentist.repository.ts
Back/src/person/dentist.service.ts
Back/src/person/dentists.controller.ts
Back/src/person/dtos/changeRoles.dto.ts
Back/src/person/dtos/createDentist.dto.ts
Back/src/person/entities/dentist.entity.ts
Back/src/person/person.controller.ts
Back/src/person/person.module.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Back/src/specialty/specialty.module.ts

Dentists CRUD

---

Back/src/auth/auth.service.ts

FIX/ add userData to the signin response

FIX/ add userData to the signin response

---

Back/src/person/entities/person.entity.ts

FIX/ add url for default photo

FIX/ add url for default photo

---

Back/src/appointments/appointments.repository.ts
Back/src/appointments/appointments.service.ts
Back/src/auth/auth.repository.ts
Back/src/auth/auth.service.ts
Back/src/person/entities/patient.entity.ts
Back/src/person/patient.controller.ts
Back/src/person/patient.repository.ts
Back/src/person/patient.service.ts
Back/src/person/person.controller.ts
Back/src/person/person.module.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts

ADD/ Patient controller, service and repository - FIX/ Spanish responses

ADD/ Patient controller, service and repository - FIX/ Spanish responses

---

Back/src/person/dentist.repository.ts
Back/src/person/patient.repository.ts
Back/src/person/patient.service.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Back/src/role/role.repository.ts

FIX/ Spanish responses

---

Back/src/common/service/mock_auto_load.service.ts
Back/src/db/dental_services.ts
Back/src/db/specialitiesDB.ts
Back/src/dentalServ/dentalServ.service.ts
Back/src/specialty/specialty.service.ts

add mock data for specialities and relation with services

mock data for specialities and relation with services

---

Back/src/person/patient.controller.ts
Back/src/person/patient.repository.ts
Back/src/person/patient.service.ts

ADD/ PatientByPersonId

---

Back/src/person/dentist.repository.ts
Back/src/person/dentist.service.ts
Back/src/person/dentists.controller.ts
Back/src/person/dtos/createGuest.dto.ts
Back/src/person/dtos/dentDentalServ.dto.ts
Back/src/person/entities/dentist.entity.ts
Back/src/person/person.controller.ts
Back/src/person/person.module.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts

ADD/ Functions for get dentists by DentalServ

ADD/ Functions for get dentists by DentalServ

---

Back/src/person/dentist.repository.ts
Back/src/person/dentist.service.ts
Back/src/person/dentists.controller.ts
Back/src/person/dtos/dentDentalServ.dto.ts
Back/src/person/dtos/dentDentalServArray.dto.ts

FIX/ functions for dentists by dental services

FIX/ functions for dentists by dental services

---

Back/src/appointments/appointments.service.ts
Back/src/common/service/mock_auto_load.service.ts
Back/src/person/patient.controller.ts
Back/src/person/patient.repository.ts
Back/src/person/patient.service.ts
Back/src/person/person.controller.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts

FIX/ some functions and ADD/ patientByDentist

FIX/ some functions and ADD/ patientByDentist

---

Back/src/common/service/mock_auto_load.service.ts
Back/src/db/dental_services.ts

ADD/ Preload Consulta de valoración

ADD/ Preload Consulta de valoración

---

Front/src/components/Appointments/CreateAppoinments.tsx

FIX/ create appointment

---

Back/src/files/files.module.ts
Back/src/person/dtos/newPhoto.dto.ts
Back/src/person/person.controller.ts
Back/src/person/person.module.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts

ADD/ endpoint to edit photo

---

Back/src/auth/auth.controller.ts
Back/src/auth/auth.module.ts
Back/src/auth/auth.service.ts
Back/src/auth/interceptors/confirmPass.interceptor.ts
Back/src/auth/middlewares/knowRole.ts
Back/src/person/dtos/createPerson.dto.ts
Back/src/person/dtos/updatePerson.dto.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Front/src/components/EditProfile/EditProfile.tsx
Front/src/helpers/formValidation.tsx
Front/src/utils/axiosInstance.js

Implementation for EditProfile component

Implementation for EditProfile component

---

Back/src/auth/auth.controller.ts
Back/src/config/typeorm.ts

FIX add roles authorization for updateperson

FIX add roles authorization for updateperson

---

Back/src/common/dto/paginationDto.ts

ADD/ IsOptional to AppointmentPaginationDto

ADD/ IsOptional to AppointmentPaginationDto

---

Front/src/app/administrative/page.tsx
Front/src/components/Login/Login.tsx
Front/src/helpers/decodeJwt.ts

ADD/ decodeJWT

---

Back/src/person/entities/dentist.entity.ts
Front/src/components/Account/Account.tsx
Front/src/components/LandingPage/LandingPage.tsx

FIX/ error messages for update photo and best 4 dentist in landing

FIX/ error messages for update photo and best 4 dentist in landing

---

Back/src/config/environment.ts

FIX/ dotenv call

---

Back/src/common/service/mock_auto_load.service.ts
Front/src/components/CardPatient/CardPatient.tsx
Front/src/components/PatientsList/PatientsList.tsx

FIX/ PatientList from DB

---

Front/src/components/PatientsList/PatientsList.tsx

FIX/ only with a dentist id

---

Back/src/common/service/mock_auto_load.service.ts
Back/src/db/dental_services.ts
Front/src/components/LandingPage/LandingPage.tsx

FIX/ preload dentists

---

Front/src/app/api/auth/[auth0]/route.js
Front/src/utils/config.ts

FIX/ environment variable

---

Back/src/auth/auth.controller.ts
Back/src/auth/auth.service.ts
Back/src/common/service/mock_auto_load.service.ts
Back/src/person/dentist.repository.ts
Back/src/person/dentist.service.ts
Back/src/person/dentists.controller.ts
Back/src/person/dtos/createDentistPerson.dto.ts
Back/src/person/entities/dentist.entity.ts
Back/src/person/entities/patient.entity.ts
Back/src/person/entities/person.entity.ts
Back/src/person/patient.controller.ts
Back/src/person/patient.repository.ts
Back/src/person/patient.service.ts
Back/src/person/person.controller.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Back/src/specialty/specialty.entity.ts
Front/src/components/ProfileButton/ProfileButton.tsx

ADD/ some endpoints and FIX/ functionality for change role

ADD/ some endpoints and FIX/ functionality for change role

---

Back/src/auth/auth.controller.ts
Back/src/person/dentist.service.ts
Back/src/person/dtos/createDentist.dto.ts
Back/src/person/patient.repository.ts
Back/src/person/patient.service.ts
Back/src/person/person.repository.ts
Back/src/person/person.service.ts
Front/src/components/CardTotalPatient/CardTotalPatient.tsx
Front/src/types/index.ts

ADD/ add and del roles functionality

ADD/ add and del roles functionality

---

Front/src/components/CardTotalDentist/CardTotalDentist.tsx
Front/src/components/CardTotalPatient/CardTotalPatient.tsx
Front/src/components/ProfileButton/ProfileButton.tsx
Front/src/components/TotalDentist/TotalDentist.tsx

FIX/ refresh when role is add or del and FIX/ role change modal

FIX/ refresh when role is add or del and FIX/ role change modal

---

Back/src/person/dentist.repository.ts
Front/src/components/RegisterAuth0/RegisterAuth0.tsx

FIX/ best 4 dentist and auth 0

FIX/ best 4 dentist and auth 0

---

Back/src/auth/auth.controller.ts

FIX/ endpoints protection

---

Back/src/auth/auth.controller.ts

FIX/ endpoint protection

---

Front/src/app/patients/recommendations/page.tsx

FIX/ YouTubeVideo importation

---

Back/src/appointments/appointments.controller.ts
Back/src/auth/auth.controller.ts
Back/src/dentalServ/dentalServ.controller.ts
Back/src/files/files.controller.ts
Back/src/headquarters/headquarter.controller.ts
Back/src/payments/payments.controller.ts
Back/src/person/dentist.repository.ts
Back/src/person/dentists.controller.ts
Back/src/person/patient.controller.ts
Back/src/person/person.controller.ts
Back/src/system_configs/system_configs.controller.ts
Front/src/app/admin/users/patients/[patientId]/page.tsx
Front/src/components/NavBar/navBar.tsx
Front/src/components/PendingAppointment/FormModal.tsx
Front/src/components/Register/Register.tsx

ADD/ functionality for pending appointments from admin

ADD/ functionality for pending appointments from admin

---

Back/src/auth/auth.repository.ts
Back/src/auth/auth.service.ts

FIX/ softDelete

---

Back/src/auth/auth.service.ts
Back/src/person/dentist.repository.ts
Back/src/person/dentist.service.ts
Back/src/person/dentists.controller.ts
Back/src/person/dtos/updatePerson.dto.ts
Front/src/components/Account/Account.tsx
Front/src/components/Calendar/CalendarAppointments.tsx
Front/src/components/Calendar/ModalNuevaCita.tsx
Front/src/components/EditProfile/EditProfile.tsx
Front/src/components/PendingAppointment/FormModal.tsx
Front/src/helpers/formValidation.tsx

FIX/ edit profile and only active dentists

FIX/ edit profile and only active dentists

---

Back/src/dentalServ/dentalServ.controller.ts
Front/src/components/Calendar/ModalNuevaCita.tsx
Front/src/components/Citas/Citas.tsx
Front/src/components/EditProfile/EditProfile.tsx

- pastAppointments
- create service as dentist
- time in swal message from administrative, when an appointment is created
- edit profile

FIX/ some fixes

---

Back/src/mail/mail.service.ts
Front/src/components/PendingAppointment/FormModal.tsx

FIX/ nodemailer and modal for pending appointments

FIX/ nodemailer and modal for pending appointments

---

Back/src/auth/auth.controller.ts
Back/src/auth/auth.module.ts
Back/src/auth/auth.repository.ts
Back/src/auth/auth.service.ts
Back/src/auth/dtos/restorePassword.dto.ts
Back/src/auth/entities/auth.entity.ts
Front/src/app/restore-password/page.tsx
Front/src/components/Login/Login.tsx
Front/src/components/RestorePassword/RestorePassword.tsx
Front/src/components/RestorePasswordInfo/RestorePasswordInfo.tsx

Restore password

---

Back/src/auth/auth.service.ts
Front/src/app/users/password/page.tsx
Front/src/components/ChangePassword/ChangePassword.tsx
Front/src/components/Password/Password.tsx
Front/src/components/ProfileButton/ProfileButton.tsx
Front/src/helpers/formValidation.tsx
Front/src/types/index.ts

Change password functionality

---

Back/src/person/dentist.repository.ts
Back/src/person/dentist.service.ts
Back/src/person/dentists.controller.ts
Front/src/components/Calendar/ModalNuevaCita.tsx
Front/src/components/PendingAppointment/FormModal.tsx

ADD/ dentalServicesWithDentist

ADD/ dentalServicesWithDentist

---

Front/src/components/Payments/PaymentsHistory.tsx

FIX/ pay date
